### ISSUE TITLE
Component - Multi Choice - Using structural markup in a way that does not represent relationships in the content

### ISSUE THREAD

**Issue by GGD4V** [MeD-DMC/Adapt-accessibilityfixes#101]
Issue: The radio buttons under "In What Ways Are You Privileged" are not coded as actual HTML radio buttons, making the form hard to use as the controls are not universal.

**Comment by GGD4V** [comment]
because they are checkboxes, not radio buttoins.

**Comment by GGD4V** [comment]
THis has resurfaced as part of latest report.

**Comment by Tamayuzu** [comment]
Call the guy to ask what's up

**Comment by Tamayuzu** [comment]
Maxim cleared it as false positive from last report
