### ISSUE TITLE
General - popups - Tabindex="0" on non-interactive component

### ISSUE THREAD

**Issue by GGD4V** [MeD-DMC/Adapt-accessibilityfixes#102]
Issue: I'm not sure if tabindex="0" is the problem here, but somehow when popup windows appear (like "Which types of privilege do you enjoy"), the heading get the focus, and my screen reader tells me that it's an interactive component while it's not. Solution: Make sure you're not using any aria or tabindex that makes the browser or a screen reader think that the heading is an interactive component.

Note: also affects narrative

**Comment by MeD-Owner** [comment]
Melissa will re-check

**Comment by Tamayuzu** [comment]
Could not verify, added aria-disabled="true" but no idea if it will work or not depending on the screen reader.

**Comment by Tamayuzu** [comment]
Did not return in latest report! Closing
