### ISSUE TITLE
Components - Slideshow/Narrative - Should be controllable with keyboard

### ISSUE THREAD

**Issue by GGD4V** [MeD-DMC/Adapt-accessibilityfixes#103]
Issue: The slideshow widget under "What Being Privileged Does NOT Mean" should have multiple ways to be controlled. We should be able to change slides with our keyboard arrows instead of dealing with tab forward click, tab back click...

**Comment by MeD-Owner** [comment]
Add code to control it with Keyboard

**Comment by GGD4V** [comment]
Already works with keyboard on tab and enter press. 
W3C example does not give a carousel requiring keyboard arrows, hence not an immediate requirement. 

https://www.w3.org/WAI/tutorials/carousels/working-example/

**Comment by GGD4V** [comment]
Another w3c sample that doesn't seem to require arrow keys functions. 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/carousel/carousel-1.html

**Comment by MaximPerry** [comment]
Arrow keys control is more of a "should" than a "must". What's really important here is that the carousel is keyboard accessible and intuitive. In those two example, they are:

https://www.w3.org/TR/wai-aria-practices-1.1/examples/carousel/carousel-1.html 
https://www.w3.org/WAI/tutorials/carousels/working-example/

Tab forward + space / enter = next slide, and tab back + space / enter = previous slide. You can see the visual focus indicator just fin, and the carousel controls are usable using only the keyboard. in Adapt however, it's not so obvious how to access the carousel controls. Then my focus is on "next slide", I intuitively hit Shift Tab to select the "previous slide" button but my focus gets lost elsewhere. Or after I successfully changed the slide, my focus is else where, no longer on the "Next slide" button...

**Comment by GGD4V** [comment]
was fixed here. https://github.com/MeD-DMC/Adapt-accessibilityfixes/commit/8e62b1ac253591ccd7a62e41811bbfc124d0e3cb

Should now be more intuitive when focus returns to either the arrow button that was used or the one that is not narrative-hidden for a similar experience than carousel given by W3C.
