### ISSUE TITLE
Focus Indicator Disappears While Tabbing

### ISSUE THREAD

**Issue by GGD4V** [MeD-DMC/Adapt-accessibilityfixes#104]
Observation: I notice that the website has it's own visual focus indicator in red, which disappears from time to time leaving only the default HTML focus indicator visible, like on "Show transcript" button under the video.

**Comment by GGD4V** [comment]
Prob in theme fix. Make sure all focus receives proper CSS.

**Comment by Tamayuzu** [comment]
Moved to https://github.com/MeD-DMC/adapt-contrib-esdc-college-theme/issues/29

**Comment by Tamayuzu** [comment]
Forced it in JS for now, 99% good but still disappears on the first popup on each page and the first time you navigate to the skip to content button.
