### ISSUE TITLE
An invisible element gets keyboard focus in the middle of and operation - 2.4.3 Focus order (Level A)

### ISSUE THREAD

**Issue by MaximPerry** [MeD-DMC/Adapt-accessibilityfixes#115]
Issue: 
When opening the right-side menu using the keyboard, the first element to get the focus is not the first menu element but an invisible `<div class="aria-label">`.

How to fix: 
I personally don't see the utility of having this DIV there. I would advice removing it (thus also removing its functionality) and instead adding the aria-label on the first menu element getting in focus for additional info.

Where: https://esdcadapt.canadacentral.cloudapp.azure.com/preview/5dc446fd27f08836496b6b9e/609bf3f10f1c9f0f267729d3/ 

![image](https://user-images.githubusercontent.com/28932114/125305414-532c9a00-e2fc-11eb-82cd-068373120e20.png)
![image](https://user-images.githubusercontent.com/28932114/125305532-663f6a00-e2fc-11eb-849c-b62118f4edd3.png)

Link to issue in ICT DCS: http://esdc.prv/cgi-bin/scdtic-ictdcs/error-view.aspx?eid=126&aid=347

**Comment by GGD4V** [comment]
When removing this div the focus goes automatically on the first item instead (in this case Glossary)

**Comment by GGD4V** [comment]
Fixed here https://github.com/MeD-DMC/Adapt-accessibilityfixes/commit/c5c94991faa4a04a5e3fd41a6cfc824f6b3a03da
