### ISSUE TITLE
Skip to transcript JS fix

### ISSUE THREAD

**Issue by GGD4V** [MeD-DMC/Adapt-accessibilityfixes#116]
Issue: The "Skip to transcript" button should be a link (<a> or role="link") since it's an anchor, and it should be clearly styled like a link. Its currently not discernible in the text.

**Comment by Tamayuzu** [comment]
Does it really need to be? is it not ok for a button to anchor? Check with Melissa

**Comment by Tamayuzu** [comment]
Using a anchor tag was breaking the page entirely due the way Adapt uses the address bar. After verifying that the WET templates do not have a skip to transcript button on their media component, we removed it from Adapt's media component as well.
