### ISSUE TITLE
Component - Accordion - Design Pattern

### ISSUE THREAD

**Issue by falcochip** [MeD-DMC/Adapt-accessibilityfixes#120]
2.1 MeD: Global – Accordian Issues (4.1.2) 

Accordions, when run through Accessibility Insights will report an error due to their design patterns not being recognized as accessible. There may be other elements that contain design pattern issues, we are currently looking into this. 

We currently have a team looking into possible solutions as this is a recent discovery. More information will be added in regards to a solution as soon as one is found. This requires further research.

**Comment by MeD-Owner** [comment]
Same as #145, closing
