### ISSUE TITLE
Component - Narrative - role & aria-level

### ISSUE THREAD

**Issue by farheenhalani** [MeD-DMC/Adapt-accessibilityfixes#122]
2.3 MeD: Page contains Heading “0” (1.3.1)  
Narrative component has role="heading" then adding an aria-level = 0
Recommendation = "We recommend replacing all with an H3 heading. "

Not exactly a heading so maybe set role = "note"/"widget"

**Comment by farheenhalani** [comment]
2.2 MeD: Narrative - aria-valid-attr-value (4.1.1, 4.1.2)  
2.10 MeD: aria-valid-attr-value (2.1.1)  see screenshot
ARIA attributes must have valid values. 

Path 

`.narrative-content-item.visited[data-index="\33 "] > .narrative-content-title > .narrative-content-title-inner[aria-level="\30 "][role="heading"] 
`
Snippet 

`<div class="narrative-content-title-inner" role="heading" aria-level="0"> What should you do? </div> `

dunno where the path is coming from - not in JS

Might be because aria-level="0" is invalid for role="heading"

**Comment by Tamayuzu** [comment]
Would we want to add aria-live to alert the screen reader that something changed?

We need to talk to Melissa about this one, should you use a narrative with a header but NO content
