### ISSUE TITLE
Button - Alt text diff than displayed text

### ISSUE THREAD

**Issue by falcochip** [MeD-DMC/Adapt-accessibilityfixes#124]
2.6 MeD: Button's alt text different than visually displayed text (1.3.1, 2.5.3)

Make sure all of the widget's visible label and instructions are included in its accessible name/description
alt text for "Next" button is "Next page incomplete"

to check with melissa abt button - should we add code to auto copy labels?

**Comment by Tamayuzu** [comment]
Next (and previous) page can be removed manually - 
Talk to Melissa - should we add this to best practices?
 We can't remove "incomplete"

**Comment by Tamayuzu** [comment]
Should be Next Page / Previous Page

**Comment by ftourangeau** [comment]
These have been added to the Adapt Best Practices Guide.
