### ISSUE TITLE
Extension - Trickle - Sometimes page doesn't scroll to the right location

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#13]
Page not shifting down completely to where the keyboard focus is located (IE only?)

**Comment by GGD4V** [comment]
I'll put this on re-test. If it is IE only and support will be dropped shortly. No use fixing it for that short of a term.

**Comment by Tamayuzu** [comment]
Seems like we broke this code, now it never shifts down

**Comment by Tamayuzu** [comment]
It's a setting, let's put it as a default (Scroll Automatically)

**Comment by MeD-Owner** [comment]
A11Y network discussing it

**Comment by ftourangeau** [comment]
Now part of best practices
