### ISSUE TITLE
hotgrid and hotgraphic close tab stuck

### ISSUE THREAD

**Issue by GGD4V** [MeD-DMC/Adapt-accessibilityfixes#134]
Hi. I think this is a temporary fix for another issue that if that option is unticked then when we tab to the close button we are stuck there and can't tab off of it. If I recall correctly another issue when it was unticked is that the previous or next buttons don't always appear when navigating through the pins.

Having it ticked it also to allow users to make sure they have seen all the pins. if they did not start off on the first one then they could miss it and not realise it. I saw this happen with a tester from Fable.

I know it is not great user experience, but having keyboard users get stuck is worse.

**Comment by MeD-Owner** [comment]
No idea what this means anymore, closing.
