### ISSUE TITLE
Component - Narrative - something with headings [OHS 2.10, 2.11]

### ISSUE THREAD

**Issue by Tamayuzu** [MeD-DMC/Adapt-accessibilityfixes#143]
Impact on Learner:  

When an assistive technology encounters an element with an invalid ARIA attribute value, it might ignore the attribute or respond to it in an unexpected way. As a result, people who use assistive technologies might find the element difficult or impossible to use. 

Details, screenshots, coding:  

n/a heading is given a ‘0’ in the heading field in Adapt for the component in Adapt. Should instead be given an (Aria) level 3 as it is a subsection of a heading level 2 section; H0 (zero) does not exist in html.  

Vincent: Is there an issue with the script to proscribe heading levels or is it a mistake on the part of the designer?  

https://accessibilityinsights.io/info-examples/web/aria-valid-attr-value/

**Comment by Tamayuzu** [comment]
Impact on Learner: Having more than one H1 per page will confuse screen readers. The single H1 should concisely describe the overall purpose of the page content.

**Comment by MeD-Owner** [comment]
This may already be fixed

**Comment by jonahxu** [comment]
Everything seems good!
