### ISSUE TITLE
Component - Multiple Choice - auto-scroll

### ISSUE THREAD

**Issue by Tamayuzu** [MeD-DMC/Adapt-accessibilityfixes#148]
https://esdcadapt.canadacentral.cloudapp.azure.com/preview/5dc446fd27f08836496b6b9e/615212d08177ea0c96c3e26c/#/id/615212d08177ea0c96c3e26e

Clicking ShowAnswer / MyAnswer scrolls the page upwards

**Comment by ftourangeau** [comment]
Fixed in release Adapt-accessibilityfixes 0.5.6
