### ISSUE TITLE
All Components - &nbsp;

### ISSUE THREAD

**Issue by Tamayuzu** [MeD-DMC/Adapt-accessibilityfixes#151]
Sometimes, in component bodies, using a space will get converted to &nbsp;

Should we convert them to a regular space automatically

How are they getting added automatically?

**Comment by falcochip** [comment]
alternative for CK editor?
Disable code from config settings?

**Comment by jonahxu** [comment]
`document.body.innerHTML = document.body.innerHTML.replace(/&nbsp;/g, " ");`

**Comment by ftourangeau** [comment]
Duplicate issue of #163
