### ISSUE TITLE
Narrative Strapline

### ISSUE THREAD

**Issue by graphicidentity** [MeD-DMC/Adapt-accessibilityfixes#159]
Can the Narrative Strapline be also added to the Hotgrid (and other components) to replace "Popup Title"? I noticed the Strapline does a much better job display Title in the top blue bar. With the other components, the Title text remains the same size as the paragraph text, and it not as helpful I think for visually impaired learners.
@Tamayuzu @ftourangeau 

#narrativestrapline #Adapt #Titletext #magnification #400

**Comment by falcochip** [comment]
hot grid title have minor improvements so this may not be necessary anymore
