### ISSUE TITLE
Component - MultiChoice - Tab and focus

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#168]
Can no longer tab through or see focus on MultiChoice questions

Looks like the Multichoice accessibility fixes no longer run at all, could just be something small in the code, may have been introduced in the ie11 revision

**Comment by falcochip** [comment]
the tabbing works if it is checkbox multichoice
it doesnt tab if its radio (but can use arrows)
add CSS to college theme to add focus outline to options

**Comment by falcochip** [comment]
https://github.com/MeD-DMC/adapt-esdc-college-theme/commit/49a3a4e06731a2696e8973fc229bdf623b374c67
