### ISSUE TITLE
All - slowdowns

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#169]
When a page is really big / contains a lot of interactions, there is a lag time when closing the popup.

Happens even when accessibility fixes is off so it's in the core of Adapt.

**Comment by falcochip** [comment]
this code was to change focus on error - prolly for WSCOE
comment out the following
 ` //Only trigger if instructions exist and not empty
            if (instrfocus.length > 0 && !(instrfocus.html() == "")) {
                $([document.documentElement, document.body]).animate({
                    scrollTop: instrfocus.offset().top - (window.innerHeight / 2)
                }, 200);
            }`
