### ISSUE TITLE
Component - Audio

### ISSUE THREAD

**Issue by Tamayuzu** [MeD-DMC/Adapt-accessibilityfixes#171]
The MP3 audio files play fine within the Adapt Authoring Tool, but when pressing play in the audio player in a course preview or in an exported SCORM package, only a brief snippet plays before the player stops.  You can click the play button multiple times and watch and listen as the playhead advances slightly and then stops.  Only once have I had it continue playing, but as soon as I paused it, it went back to playing only a snippet at a time.  I experienced the same thing in Microsoft Edge, IE 11, Chrome and Firefox.

Here is a link to preview of the course where you can try it.  The first block on both pages 3 and 4 has a media component that should play an MP3.
https://esdcadapt.canadacentral.cloudapp.azure.com/preview/5dc446fd27f08836496b6b9e/620ea18828d48c21bd6de7ae/#/

**Comment by falcochip** [comment]
only happens if the setting - 'Pause playback when video is no longer in view' is enabled
