### ISSUE TITLE
Component - OpenText

### ISSUE THREAD

**Issue by falcochip** [MeD-DMC/Adapt-accessibilityfixes#177]
The textbox is not programmatically associated to a question / label

Tabbing order issues - buttons-action has aria-hidden when submitted

![Screen Shot 2022-04-17 at 7 53 21 PM](https://user-images.githubusercontent.com/78871138/163736813-0e57eb16-f613-47e4-baa3-df5be419f7b3.png)

**Comment by ftourangeau** [comment]
Fixed in release Adapt-accessibilityfixes 0.5.6
