### ISSUE TITLE
Focus visible indicator line width too thin and contrast and too low. 

### ISSUE THREAD

**Issue by graphicidentity** [MeD-DMC/Adapt-accessibilityfixes#185]
Recommend increasing line width by 4pixels and changing colour to provide greater contrast. Contrast is especially weak when focus indicator is on multiple choice options.

**Comment by graphicidentity** [comment]
In order to stay within College existing Adapt colour scheme - propose using Hex Colour: #EA65A0  (pink) from Article Level heading icon. This meets contrast of 3:1 against both adjacent colours (white and dark blue). Also recommend increasing line with to 3px - 5px if possible and after testing.

**Comment by ftourangeau** [comment]
Fixed in release adapt-esdc-college-theme 1.6.7 - Nov 2022
