### ISSUE TITLE
Component - Narrative - Indication that content has changed

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#23]
As you navigate through the slides, the narrative should be read out loud every time it changes.
Should maybe add an aria-live attribute on the text box?

**Comment by GGD4V** [comment]
aria-live added to narrative-content div.

**Comment by MeD-Owner** [comment]
Were there any Narrative components in RDI ?

If yes then maybe this issue is considered fixed
