### ISSUE TITLE
Component - Accordion - + / - buttons

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#4]
From Melissa:

I think the fix is so that the buttons are only + and -, depending whether the accordion is open or closed.

- Not sure if this was in WS COE report

**Comment by GGD4V** [comment]
I am not sure what the issue is here. the + and - posses aria-hidden true attribute and the accordion button communicates state via aria-expanded.

**Comment by MeD-Owner** [comment]
No issues about + or - in RDI, we can assume this is not an issue anymore
