### ISSUE TITLE
CSS issue - Focus

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#5]
From Melissa:
Focus color is not good, needs more contrast with blue buttons

It does not work for the expose component.
It does not work for the media player buttons.
It does not work for the Graphical multiple choice question, but it does work for most of the other questions. 

Suggest adding white border around the pink? To check with Melissa

**Comment by GGD4V** [comment]
Sorry, this needs to be addressed in the template directly. In fact, anything that affects the visual exp should be in the template package.

**Comment by MeD-Owner** [comment]
Moved to
https://github.com/MeD-DMC/adapt-contrib-esdc-college-theme/issues/
