### ISSUE TITLE
Component - Media - Can't tab to "skip to transcript" button [RDI 2.26]

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#52]
In all browsers, the button “skip to transcript” has a value of –1. This means that it is not in the tabbing order and can only be reached using the arrow keys when navigating the page.

**Comment by MeD-Owner** [comment]
We recommend making the “Skip to transcript” button visible and accessible (in the tabbing order) for all users. There may be many users who don’t want to view/listen to the video and skipping to the transcript button allows them to bypass all of the video player buttons. Otherwise, reaching the transcript could require many keystrokes. People with limited mobility could find this task difficult or painful, and people who use screen readers could find it tedious to listen as each repeated element is announced.

**Comment by GGD4V** [comment]
Can't have skip to transcript issue if it doesn't exists.

**Comment by MeD-Owner** [comment]
We should instead change the tabbing order!

**Comment by GGD4V** [comment]
Fixed.
