### ISSUE TITLE
Back button - same name

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#61]
There are two back links that have the same name on the page, but they have different behaviours. The one at the top of the page is for going back to the previous page we saw. The one in the Narrative tool is to go back to the previous slide/image.
Both buttons (links) have the same name “Previous”.

There is a subtle difference between the two buttons. 

The one in the navigation header is announced as “Back link” or “link back”.

The one in the narration component is announced as “Back button” when we tab to it we will also hear “to activate press enter”.

**Comment by MeD-Owner** [comment]
Can possible be changed in Adapt itself? but would be good to have a standard

**Comment by GGD4V** [comment]
Share same value in adapt than global settings back label

**Comment by GGD4V** [comment]
fixed https://github.com/MeD-DMC/Adapt-accessibilityfixes/commit/73400f41a2189cd9bf2c063eaaf8a5bfae8986de
