### ISSUE TITLE
Dialogue boxes (All popups) - Sometimes able to tab out of it [RDI 2.43]

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#7]
Using the keyboard, when you activate the dialogue box, you should not be able to tab outside of the box. The keyboard should be trapped into the dialogue until the box is closed by either hitting escape or auctioning the X to close it. 

Would need to build a tab trap

**Comment by GGD4V** [comment]
Tab trapped was added an work with generic notification events and hotgraphic hot fix was applied. Needs testing to close.

**Comment by MeD-Owner** [comment]
Page / URL: 5, 6 (IE11, Chrome) (Hot grids for Edge)

The issue is that the user can tab away from the modal window.
Users must not be able to tab away from a modal dialog without explicitly dismissing it.
The purpose of a modal dialog is to constrain user input (temporarily) to controls within the dialog. Just as mouse users should not be able to click elements outside the dialog, keyboard users should not be able to Tab to elements outside the dialog.
The screen capture below shows an example of the user tabbing out of the hot graphic modal window.
In Chrome, the focus went to the close button of the course, which if selected will close the course. Note that this only happened as of pin 2, where there is supposed to be a back navigation arrow.

Edge seems to have the similar issues as IE11, except it is limited to the Hot grid items. After tabbing through the browser items the focus goes into the page header navigation section. Once we have tabbed through the header navigation we are brought back to the modal window. Then the tabbing leaves again to the browser tab and the full cycle continues. This applies to all pins.
