### ISSUE TITLE
General - Focus - not scrolling [RDI 2.42]

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#79]
In both IE11 and Chrome, this issue occurs for videos and questions. It seems to be fine for accordions, hot grids and hot graphics. 

As the user tabs from object to object, the focus doesn't always scroll the page properly.

This problem (page not shifting down completely to where the keyboard focus is located) occurs throughout multiple pages in this course.

**Comment by GGD4V** [comment]
Goes into theme. `.mejs-offscreen {
    clip: unset !important;
    clip-path: unset !important;
}`

**Comment by MeD-Owner** [comment]
Moved to CSS issues
https://github.com/MeD-DMC/Adapt-accessibilityfixes/issues/79

**Comment by MeD-Owner** [comment]
It's both a CSS and JS issue, reopening and keeping the CSS part opened as well

**Comment by MeD-Owner** [comment]
Scrolling fixes done now relate to #76

Keeping this one open for other more general focus scrolling issues
