### ISSUE TITLE
Dialogue boxes (All popups) - When content is too long, can't scroll

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#8]
Users who use a higher magnification or use mobile may have a hard time navigating to see the entire content.

**Comment by GGD4V** [comment]
Was not able to re-create. Would be nice to have specific browser, zoom magnification levels, etc. Then we'd be able to fix it.

**Comment by MeD-Owner** [comment]
Back in latest issue report:

In Chrome, Edge and IE11 while viewing the content at 200%, the issue is with the pop-outs for Hot grids and hot graphics. I am not able to scroll down the information with a mouse. On the other hand, a keyboard user can press the page down or page up key.

(Pop-up has a big image and a few paragraphs of text)

**Comment by MeD-Owner** [comment]
Needs more CSS to be able to scroll all the way down, resize the window to fit available vw and allow scrolling when mousing over the edges. Moved these to CSS issues
