### ISSUE TITLE
Component - hotgrid - images with no alt [RDI 2.47]

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#80]
Details, screenshots, coding: An <img> element must have alternative text (which can be nul, alt=””). 

Because assistive technologies can’t interpret an image directly, they rely on alternative text to communicate the image's meaning to users. If an image has (non-empty) alternative text, the image is identified as meaningful, and its alternative text is presented to the user. If an image has an empty alt attribute, the image is identified as decorative and ignored. If an image has no alternative text at all, the image is presumed to be meaningful, and its filename is likely to be presented to the user. 

How to fix 

Determine whether the image is meaningful or decorative: 
An image is meaningful if it conveys information that isn’t available through other page content. 
An image is decorative if it could be removed from the page with no impact on meaning or function. 
If the <img> element is decorative, provide an empty alt attribute ( alt="" ). 
If the <img> element is meaningful, provide descriptive alternative text using one of the following methods: 

**Good** 
title attribute 

**Better** 
aria-label 
aria-labelledby attribute 

**Best** 
alt attribute 

Could just be something our alt tag code is skipping over?

This was flagged as an issue in the French RDI, but not the English RDI. 
**2021/04/11 - DT** 
Please note the French and English is currently programmed the same way in Adapt. If it’s not an issue for the English, why would it be an issue for the French. No corrections made, waiting on review of flagged error...

**Comment by GGD4V** [comment]
I tested hotgrid again and the empty alt text works. I presume she has tested this in IE11 where mutation observers were not working properly.
