### ISSUE TITLE
Long descriptions for images.

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#9]
Currently there is no clear way to display long descriptions.

need to consider how to include a spot for long descriptions for images.

**Comment by GGD4V** [comment]
Even if we were to add it as an attribute. I feel most users would just add a longer alt which is not the exact purpose of longdesc. How about adding one accordion below with class "longdesc". It would: 

- Remove a bunch of component styles to make the accordion appear right below previous component
- We could actually take this accordion component internal link and dynamically add to previous component (when class longdesc exists)

**Comment by MeD-Owner** [comment]
Corporate kinda does this already using combineblock class

Something we could do for sure

**Comment by GGD4V** [comment]
Might re-visit. Designers are expected to place transcript right below image.

**Comment by MeD-Owner** [comment]
Moved to 
https://github.com/MeD-DMC/adapt-contrib-esdc-college-theme/issues/4
