### ISSUE TITLE
Content auto-translation

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/Adapt-accessibilityfixes#90]
Sometimes content gets auto-translated in the wrong way

For example translator is set to translate english to french

But it detects words that seem to be in english in a french course and tries to convert them to french again (very wrongly)

For solutions:
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/prevent-translation
https://stackoverflow.com/questions/63846687/how-to-prevent-edge-from-translating-a-webpage
https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome

**Comment by GGD4V** [comment]
fixed with auto translation in Chrome and Edge.
